spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
  profiles:
    active: local

#  data:
#    cassandra:
#      keyspace-name: taco-cloud
#      schema-action: recreate
#      local-datacenter: datacenter1
#      contact-points:
#        - casshost-1.tacocloud.com
#        - casshost-2.tacocloud.com
#        - casshost-3.tacocloud.com
#      port: 9042
